### ISSUE TITLE
Move pr_verify into .github/workflows directory

### ISSUE THREAD

**Issue by jimmyblizzard** [JimBlizzard/oh1#15]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> PR does not trigger issue verify

### Any log messages given by the failure
> NA

### Expected/desired behavior
> PR should trigger issue verify

### OS and Version?
> na

### Versions
>

**Comment by JimBlizzard** [comment]
Patch worked correctly.
